# Generated by Django 4.2.6 on 2024-02-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePage', '0003_alter_card_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
