# Generated by Django 4.2.6 on 2024-02-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePage', '0004_alter_card_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='pic',
            field=models.ImageField(upload_to='images/% Y/% m/% d/'),
        ),
    ]
