# Generated by Django 4.2.6 on 2024-03-06 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GamePage', '0005_alter_card_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Creator',
        ),
    ]
