# Generated by Django 4.2.6 on 2024-03-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePage', '0006_delete_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='link',
            field=models.CharField(default='Text', max_length=150),
        ),
        migrations.AddField(
            model_name='card',
            name='text',
            field=models.CharField(default='Text', max_length=500),
        ),
        migrations.AlterField(
            model_name='card',
            name='date',
            field=models.IntegerField(),
        ),
    ]
