# Generated by Django 5.0.4 on 2024-04-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamePage', '0007_card_link_card_text_alter_card_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='link',
            field=models.CharField(default='Text', max_length=300),
        ),
        migrations.AlterField(
            model_name='card',
            name='pic',
            field=models.CharField(default='Text', max_length=300),
        ),
    ]
